// Mocks generated by Mockito 5.4.6 from annotations
// in habitly/test/features/groups/presentation/bloc/group_detail_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:habitly/features/groups/domain/entities/group_entity.dart'
    as _i3;
import 'package:habitly/features/groups/domain/entities/group_invite_entity.dart'
    as _i9;
import 'package:habitly/features/groups/domain/repositories/group_repository.dart'
    as _i2;
import 'package:habitly/features/groups/domain/usecases/get_group_details.dart'
    as _i4;
import 'package:habitly/features/groups/domain/usecases/leave_group.dart'
    as _i6;
import 'package:habitly/features/groups/domain/usecases/remove_member.dart'
    as _i7;
import 'package:habitly/features/groups/domain/usecases/send_reaction.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGroupDetail_0 extends _i1.SmartFake implements _i2.GroupDetail {
  _FakeGroupDetail_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGroupEntity_1 extends _i1.SmartFake implements _i3.GroupEntity {
  _FakeGroupEntity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetGroupDetails].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetGroupDetails extends _i1.Mock implements _i4.GetGroupDetails {
  MockGetGroupDetails() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.GroupDetail> call(
    String? groupId,
    String? currentUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            groupId,
            currentUserId,
          ],
        ),
        returnValue: _i5.Future<_i2.GroupDetail>.value(_FakeGroupDetail_0(
          this,
          Invocation.method(
            #call,
            [
              groupId,
              currentUserId,
            ],
          ),
        )),
      ) as _i5.Future<_i2.GroupDetail>);
}

/// A class which mocks [LeaveGroup].
///
/// See the documentation for Mockito's code generation for more information.
class MockLeaveGroup extends _i1.Mock implements _i6.LeaveGroup {
  MockLeaveGroup() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> call(
    String? groupId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            groupId,
            userId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [RemoveMember].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveMember extends _i1.Mock implements _i7.RemoveMember {
  MockRemoveMember() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> call(
    String? groupId,
    String? memberId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            groupId,
            memberId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [SendReaction].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendReaction extends _i1.Mock implements _i8.SendReaction {
  MockSendReaction() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> call({
    required String? groupId,
    required String? fromUserId,
    required String? toUserId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #groupId: groupId,
            #fromUserId: fromUserId,
            #toUserId: toUserId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [GroupRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupRepository extends _i1.Mock implements _i2.GroupRepository {
  MockGroupRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.GroupEntity>> getUserGroups(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserGroups,
          [userId],
        ),
        returnValue:
            _i5.Future<List<_i3.GroupEntity>>.value(<_i3.GroupEntity>[]),
      ) as _i5.Future<List<_i3.GroupEntity>>);

  @override
  _i5.Future<_i2.GroupDetail> getGroupDetails(
    String? groupId,
    String? currentUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupDetails,
          [
            groupId,
            currentUserId,
          ],
        ),
        returnValue: _i5.Future<_i2.GroupDetail>.value(_FakeGroupDetail_0(
          this,
          Invocation.method(
            #getGroupDetails,
            [
              groupId,
              currentUserId,
            ],
          ),
        )),
      ) as _i5.Future<_i2.GroupDetail>);

  @override
  _i5.Future<void> leaveGroup(
    String? groupId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #leaveGroup,
          [
            groupId,
            userId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeMember(
    String? groupId,
    String? memberId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMember,
          [
            groupId,
            memberId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> sendReaction(
    String? groupId,
    String? fromUserId,
    String? toUserId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendReaction,
          [
            groupId,
            fromUserId,
            toUserId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.GroupEntity> createGroup({
    required String? creatorUserId,
    required String? name,
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createGroup,
          [],
          {
            #creatorUserId: creatorUserId,
            #name: name,
            #description: description,
          },
        ),
        returnValue: _i5.Future<_i3.GroupEntity>.value(_FakeGroupEntity_1(
          this,
          Invocation.method(
            #createGroup,
            [],
            {
              #creatorUserId: creatorUserId,
              #name: name,
              #description: description,
            },
          ),
        )),
      ) as _i5.Future<_i3.GroupEntity>);

  @override
  _i5.Future<void> inviteUser({
    required String? groupId,
    required String? fromUserId,
    required String? toUsername,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #inviteUser,
          [],
          {
            #groupId: groupId,
            #fromUserId: fromUserId,
            #toUsername: toUsername,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i9.GroupInviteEntity>> getPendingInvites(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingInvites,
          [userId],
        ),
        returnValue: _i5.Future<List<_i9.GroupInviteEntity>>.value(
            <_i9.GroupInviteEntity>[]),
      ) as _i5.Future<List<_i9.GroupInviteEntity>>);

  @override
  _i5.Future<void> decideInvite({
    required String? inviteId,
    required String? userId,
    required bool? accept,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #decideInvite,
          [],
          {
            #inviteId: inviteId,
            #userId: userId,
            #accept: accept,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<Map<String, dynamic>>> searchUsers(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchUsers,
          [query],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> deleteGroup(
    String? groupId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteGroup,
          [
            groupId,
            userId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
