// Mocks generated by Mockito 5.4.6 from annotations
// in habitly/test/features/habits/presentation/pages/edit_habit_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:habitly/features/home/domain/entities/today_habit_entity.dart'
    as _i4;
import 'package:habitly/features/home/domain/repositories/home_repository.dart'
    as _i6;
import 'package:habitly/features/home/domain/usecases/delete_habit.dart' as _i8;
import 'package:habitly/features/home/domain/usecases/get_habit_by_id.dart'
    as _i2;
import 'package:habitly/features/home/domain/usecases/get_home_group_filter_options.dart'
    as _i5;
import 'package:habitly/features/home/domain/usecases/upsert_habit_definition.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetHabitById].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetHabitById extends _i1.Mock implements _i2.GetHabitById {
  MockGetHabitById() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.TodayHabitEntity?> call(
    String? habitId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            habitId,
            userId,
          ],
        ),
        returnValue: _i3.Future<_i4.TodayHabitEntity?>.value(),
      ) as _i3.Future<_i4.TodayHabitEntity?>);
}

/// A class which mocks [GetHomeGroupFilterOptions].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetHomeGroupFilterOptions extends _i1.Mock
    implements _i5.GetHomeGroupFilterOptions {
  MockGetHomeGroupFilterOptions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i6.HomeGroupFilterOption>> call(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [userId],
        ),
        returnValue: _i3.Future<List<_i6.HomeGroupFilterOption>>.value(
            <_i6.HomeGroupFilterOption>[]),
      ) as _i3.Future<List<_i6.HomeGroupFilterOption>>);
}

/// A class which mocks [UpsertHabitDefinition].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpsertHabitDefinition extends _i1.Mock
    implements _i7.UpsertHabitDefinition {
  MockUpsertHabitDefinition() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(
    String? userId,
    _i4.TodayHabitEntity? habit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            userId,
            habit,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [DeleteHabitUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteHabitUseCase extends _i1.Mock
    implements _i8.DeleteHabitUseCase {
  MockDeleteHabitUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(
    String? habitId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            habitId,
            userId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
