// Mocks generated by Mockito 5.4.6 from annotations
// in habitly/test/features/home/presentation/bloc/home_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:habitly/core/error/failures.dart' as _i11;
import 'package:habitly/features/gamification/domain/entities/achievement.dart'
    as _i12;
import 'package:habitly/features/gamification/domain/repositories/gamification_repository.dart'
    as _i2;
import 'package:habitly/features/gamification/domain/usecases/complete_habit.dart'
    as _i10;
import 'package:habitly/features/home/domain/entities/today_habit_entity.dart'
    as _i6;
import 'package:habitly/features/home/domain/repositories/home_repository.dart'
    as _i8;
import 'package:habitly/features/home/domain/usecases/get_home_group_filter_options.dart'
    as _i7;
import 'package:habitly/features/home/domain/usecases/get_today_habits_for_day.dart'
    as _i4;
import 'package:habitly/features/home/domain/usecases/toggle_habit_completion.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGamificationRepository_0 extends _i1.SmartFake
    implements _i2.GamificationRepository {
  _FakeGamificationRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetTodayHabitsForDay].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTodayHabitsForDay extends _i1.Mock
    implements _i4.GetTodayHabitsForDay {
  MockGetTodayHabitsForDay() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.TodayHabitEntity>> call({
    required String? userId,
    required DateTime? day,
    String? groupId,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #userId: userId,
            #day: day,
            #groupId: groupId,
            #forceRefresh: forceRefresh,
          },
        ),
        returnValue: _i5.Future<List<_i6.TodayHabitEntity>>.value(
            <_i6.TodayHabitEntity>[]),
      ) as _i5.Future<List<_i6.TodayHabitEntity>>);
}

/// A class which mocks [GetHomeGroupFilterOptions].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetHomeGroupFilterOptions extends _i1.Mock
    implements _i7.GetHomeGroupFilterOptions {
  MockGetHomeGroupFilterOptions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i8.HomeGroupFilterOption>> call(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [userId],
        ),
        returnValue: _i5.Future<List<_i8.HomeGroupFilterOption>>.value(
            <_i8.HomeGroupFilterOption>[]),
      ) as _i5.Future<List<_i8.HomeGroupFilterOption>>);
}

/// A class which mocks [ToggleHabitCompletion].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleHabitCompletion extends _i1.Mock
    implements _i9.ToggleHabitCompletion {
  MockToggleHabitCompletion() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> call({
    required String? habitId,
    required String? userId,
    required DateTime? day,
    required bool? completed,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #habitId: habitId,
            #userId: userId,
            #day: day,
            #completed: completed,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [CompleteHabit].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompleteHabit extends _i1.Mock implements _i10.CompleteHabit {
  MockCompleteHabit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GamificationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeGamificationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.GamificationRepository);

  @override
  _i5.Future<_i3.Either<_i11.Failure, List<_i12.NewAchievementInfo>>> call(
          _i10.CompleteHabitParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<
                _i3.Either<_i11.Failure, List<_i12.NewAchievementInfo>>>.value(
            _FakeEither_1<_i11.Failure, List<_i12.NewAchievementInfo>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i11.Failure, List<_i12.NewAchievementInfo>>>);
}
