// Mocks generated by Mockito 5.4.6 from annotations
// in habitly/test/features/gamification/presentation/bloc/stats_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:habitly/core/error/failures.dart' as _i6;
import 'package:habitly/features/gamification/domain/entities/achievement.dart'
    as _i13;
import 'package:habitly/features/gamification/domain/entities/habit_stats.dart'
    as _i9;
import 'package:habitly/features/gamification/domain/entities/timeline_point.dart'
    as _i11;
import 'package:habitly/features/gamification/domain/entities/user_stats.dart'
    as _i7;
import 'package:habitly/features/gamification/domain/repositories/gamification_repository.dart'
    as _i2;
import 'package:habitly/features/gamification/domain/usecases/complete_habit.dart'
    as _i12;
import 'package:habitly/features/gamification/domain/usecases/get_habits_stats.dart'
    as _i8;
import 'package:habitly/features/gamification/domain/usecases/get_user_stats.dart'
    as _i4;
import 'package:habitly/features/gamification/domain/usecases/get_user_timeline.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGamificationRepository_0 extends _i1.SmartFake
    implements _i2.GamificationRepository {
  _FakeGamificationRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetUserStats].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserStats extends _i1.Mock implements _i4.GetUserStats {
  MockGetUserStats() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GamificationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeGamificationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.GamificationRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.UserStats>> call(
          _i4.GetUserStatsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.UserStats>>.value(
            _FakeEither_1<_i6.Failure, _i7.UserStats>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.UserStats>>);
}

/// A class which mocks [GetHabitsStats].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetHabitsStats extends _i1.Mock implements _i8.GetHabitsStats {
  MockGetHabitsStats() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GamificationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeGamificationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.GamificationRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i9.HabitStats>>> call(
          _i8.GetHabitsStatsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i9.HabitStats>>>.value(
                _FakeEither_1<_i6.Failure, List<_i9.HabitStats>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i9.HabitStats>>>);
}

/// A class which mocks [GetUserTimeline].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserTimeline extends _i1.Mock implements _i10.GetUserTimeline {
  MockGetUserTimeline() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GamificationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeGamificationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.GamificationRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i11.TimelinePoint>>> call(
          _i10.GetUserTimelineParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i11.TimelinePoint>>>.value(
                _FakeEither_1<_i6.Failure, List<_i11.TimelinePoint>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i11.TimelinePoint>>>);
}

/// A class which mocks [CompleteHabit].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompleteHabit extends _i1.Mock implements _i12.CompleteHabit {
  MockCompleteHabit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GamificationRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeGamificationRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.GamificationRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i13.NewAchievementInfo>>> call(
          _i12.CompleteHabitParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<
                _i3.Either<_i6.Failure, List<_i13.NewAchievementInfo>>>.value(
            _FakeEither_1<_i6.Failure, List<_i13.NewAchievementInfo>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i13.NewAchievementInfo>>>);
}
