// Mocks generated by Mockito 5.4.6 from annotations
// in habitly/test/features/home/domain/usecases/get_home_group_filter_options_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:habitly/features/home/domain/entities/today_habit_entity.dart'
    as _i4;
import 'package:habitly/features/home/domain/repositories/home_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i2.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.TodayHabitEntity>> getHabitsForDay({
    required String? userId,
    required DateTime? day,
    String? groupId,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHabitsForDay,
          [],
          {
            #userId: userId,
            #day: day,
            #groupId: groupId,
            #forceRefresh: forceRefresh,
          },
        ),
        returnValue: _i3.Future<List<_i4.TodayHabitEntity>>.value(
            <_i4.TodayHabitEntity>[]),
      ) as _i3.Future<List<_i4.TodayHabitEntity>>);

  @override
  _i3.Future<List<_i2.HomeGroupFilterOption>> getGroupFilterOptions(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupFilterOptions,
          [userId],
        ),
        returnValue: _i3.Future<List<_i2.HomeGroupFilterOption>>.value(
            <_i2.HomeGroupFilterOption>[]),
      ) as _i3.Future<List<_i2.HomeGroupFilterOption>>);

  @override
  _i3.Future<void> setHabitCompletedForDay({
    required String? habitId,
    required DateTime? day,
    required bool? completed,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setHabitCompletedForDay,
          [],
          {
            #habitId: habitId,
            #day: day,
            #completed: completed,
            #userId: userId,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.TodayHabitEntity?> getHabitById(
    String? habitId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHabitById,
          [
            habitId,
            userId,
          ],
        ),
        returnValue: _i3.Future<_i4.TodayHabitEntity?>.value(),
      ) as _i3.Future<_i4.TodayHabitEntity?>);

  @override
  _i3.Future<void> upsertHabitDefinition(
    String? userId,
    _i4.TodayHabitEntity? habit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertHabitDefinition,
          [
            userId,
            habit,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteHabit(
    String? habitId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteHabit,
          [
            habitId,
            userId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
