// Mocks generated by Mockito 5.4.6 from annotations
// in habitly/test/features/gamification/data/repositories/gamification_repository_impl_timeline_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:habitly/features/gamification/data/datasources/gamification_local_datasource.dart'
    as _i12;
import 'package:habitly/features/gamification/data/datasources/gamification_remote_datasource.dart'
    as _i5;
import 'package:habitly/features/gamification/data/models/achievement_model.dart'
    as _i9;
import 'package:habitly/features/gamification/data/models/group_stats_model.dart'
    as _i4;
import 'package:habitly/features/gamification/data/models/habit_stats_model.dart'
    as _i8;
import 'package:habitly/features/gamification/data/models/timeline_point_model.dart'
    as _i11;
import 'package:habitly/features/gamification/data/models/user_level_model.dart'
    as _i2;
import 'package:habitly/features/gamification/data/models/user_stats_model.dart'
    as _i3;
import 'package:habitly/features/gamification/domain/entities/achievement.dart'
    as _i10;
import 'package:habitly/features/gamification/domain/entities/user_stats.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserLevelModel_0 extends _i1.SmartFake
    implements _i2.UserLevelModel {
  _FakeUserLevelModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserStatsModel_1 extends _i1.SmartFake
    implements _i3.UserStatsModel {
  _FakeUserStatsModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGroupStatsModel_2 extends _i1.SmartFake
    implements _i4.GroupStatsModel {
  _FakeGroupStatsModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GamificationRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGamificationRemoteDataSource extends _i1.Mock
    implements _i5.GamificationRemoteDataSource {
  MockGamificationRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.UserLevelModel> getUserLevel(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserLevel,
          [userId],
        ),
        returnValue: _i6.Future<_i2.UserLevelModel>.value(_FakeUserLevelModel_0(
          this,
          Invocation.method(
            #getUserLevel,
            [userId],
          ),
        )),
      ) as _i6.Future<_i2.UserLevelModel>);

  @override
  _i6.Future<_i3.UserStatsModel> getUserStats(
    String? userId,
    _i7.StatsPeriod? period,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserStats,
          [
            userId,
            period,
          ],
        ),
        returnValue: _i6.Future<_i3.UserStatsModel>.value(_FakeUserStatsModel_1(
          this,
          Invocation.method(
            #getUserStats,
            [
              userId,
              period,
            ],
          ),
        )),
      ) as _i6.Future<_i3.UserStatsModel>);

  @override
  _i6.Future<List<_i8.HabitStatsModel>> getUserHabitsStats(
    String? userId,
    _i7.StatsPeriod? period,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserHabitsStats,
          [
            userId,
            period,
          ],
        ),
        returnValue: _i6.Future<List<_i8.HabitStatsModel>>.value(
            <_i8.HabitStatsModel>[]),
      ) as _i6.Future<List<_i8.HabitStatsModel>>);

  @override
  _i6.Future<List<_i9.AchievementModel>> getAchievements(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAchievements,
          [userId],
        ),
        returnValue: _i6.Future<List<_i9.AchievementModel>>.value(
            <_i9.AchievementModel>[]),
      ) as _i6.Future<List<_i9.AchievementModel>>);

  @override
  _i6.Future<List<_i10.NewAchievementInfo>> completeHabit(
    String? habitId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeHabit,
          [
            habitId,
            userId,
          ],
        ),
        returnValue: _i6.Future<List<_i10.NewAchievementInfo>>.value(
            <_i10.NewAchievementInfo>[]),
      ) as _i6.Future<List<_i10.NewAchievementInfo>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getGroupAchievements(
          String? groupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupAchievements,
          [groupId],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<_i4.GroupStatsModel> getGroupStats(
    String? groupId,
    _i7.StatsPeriod? period,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupStats,
          [
            groupId,
            period,
          ],
        ),
        returnValue:
            _i6.Future<_i4.GroupStatsModel>.value(_FakeGroupStatsModel_2(
          this,
          Invocation.method(
            #getGroupStats,
            [
              groupId,
              period,
            ],
          ),
        )),
      ) as _i6.Future<_i4.GroupStatsModel>);

  @override
  _i6.Future<List<_i11.TimelinePointModel>> getUserTimeline(
    String? userId,
    _i7.StatsPeriod? period,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserTimeline,
          [
            userId,
            period,
          ],
        ),
        returnValue: _i6.Future<List<_i11.TimelinePointModel>>.value(
            <_i11.TimelinePointModel>[]),
      ) as _i6.Future<List<_i11.TimelinePointModel>>);
}

/// A class which mocks [GamificationLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGamificationLocalDataSource extends _i1.Mock
    implements _i12.GamificationLocalDataSource {
  MockGamificationLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.UserLevelModel?> getCachedUserLevel(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedUserLevel,
          [userId],
        ),
        returnValue: _i6.Future<_i2.UserLevelModel?>.value(),
      ) as _i6.Future<_i2.UserLevelModel?>);

  @override
  _i6.Future<void> cacheUserLevel(_i2.UserLevelModel? level) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheUserLevel,
          [level],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.UserStatsModel?> getCachedUserStats(
    String? userId,
    _i7.StatsPeriod? period,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedUserStats,
          [
            userId,
            period,
          ],
        ),
        returnValue: _i6.Future<_i3.UserStatsModel?>.value(),
      ) as _i6.Future<_i3.UserStatsModel?>);

  @override
  _i6.Future<void> cacheUserStats(_i3.UserStatsModel? stats) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheUserStats,
          [stats],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i9.AchievementModel>?> getCachedAchievements(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedAchievements,
          [userId],
        ),
        returnValue: _i6.Future<List<_i9.AchievementModel>?>.value(),
      ) as _i6.Future<List<_i9.AchievementModel>?>);

  @override
  _i6.Future<void> cacheAchievements(
    String? userId,
    List<_i9.AchievementModel>? achievements,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheAchievements,
          [
            userId,
            achievements,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.GroupStatsModel?> getCachedGroupStats(
    String? groupId,
    _i7.StatsPeriod? period,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedGroupStats,
          [
            groupId,
            period,
          ],
        ),
        returnValue: _i6.Future<_i4.GroupStatsModel?>.value(),
      ) as _i6.Future<_i4.GroupStatsModel?>);

  @override
  _i6.Future<void> cacheGroupStats(_i4.GroupStatsModel? stats) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheGroupStats,
          [stats],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
