// Mocks generated by Mockito 5.4.6 from annotations
// in habitly/test/features/groups/presentation/pages/groups_page_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_bloc/flutter_bloc.dart' as _i8;
import 'package:habitly/features/groups/domain/entities/group_entity.dart'
    as _i3;
import 'package:habitly/features/groups/domain/usecases/create_group.dart'
    as _i9;
import 'package:habitly/features/groups/presentation/bloc/groups_bloc.dart'
    as _i4;
import 'package:habitly/features/groups/presentation/bloc/groups_event.dart'
    as _i7;
import 'package:habitly/features/groups/presentation/bloc/groups_state.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGroupsState_0 extends _i1.SmartFake implements _i2.GroupsState {
  _FakeGroupsState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGroupEntity_1 extends _i1.SmartFake implements _i3.GroupEntity {
  _FakeGroupEntity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GroupsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupsBloc extends _i1.Mock implements _i4.GroupsBloc {
  MockGroupsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get currentUserId => (super.noSuchMethod(
        Invocation.getter(#currentUserId),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#currentUserId),
        ),
      ) as String);

  @override
  _i2.GroupsState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeGroupsState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.GroupsState);

  @override
  _i6.Stream<_i2.GroupsState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i6.Stream<_i2.GroupsState>.empty(),
      ) as _i6.Stream<_i2.GroupsState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i7.GroupsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i7.GroupsEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i2.GroupsState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i7.GroupsEvent>(
    _i8.EventHandler<E, _i2.GroupsState>? handler, {
    _i8.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i8.Transition<_i7.GroupsEvent, _i2.GroupsState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(
    _i7.GroupsEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #onDone,
          [
            event,
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void onChange(_i8.Change<_i2.GroupsState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CreateGroup].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateGroup extends _i1.Mock implements _i9.CreateGroup {
  MockCreateGroup() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.GroupEntity> call({
    required String? creatorUserId,
    required String? name,
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #creatorUserId: creatorUserId,
            #name: name,
            #description: description,
          },
        ),
        returnValue: _i6.Future<_i3.GroupEntity>.value(_FakeGroupEntity_1(
          this,
          Invocation.method(
            #call,
            [],
            {
              #creatorUserId: creatorUserId,
              #name: name,
              #description: description,
            },
          ),
        )),
      ) as _i6.Future<_i3.GroupEntity>);
}
