// Mocks generated by Mockito 5.4.6 from annotations
// in habitly/test/features/gamification/domain/usecases/get_user_level_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:habitly/core/error/failures.dart' as _i5;
import 'package:habitly/features/gamification/domain/entities/achievement.dart'
    as _i9;
import 'package:habitly/features/gamification/domain/entities/group_achievement.dart'
    as _i10;
import 'package:habitly/features/gamification/domain/entities/group_stats.dart'
    as _i11;
import 'package:habitly/features/gamification/domain/entities/habit_stats.dart'
    as _i8;
import 'package:habitly/features/gamification/domain/entities/user_level.dart'
    as _i6;
import 'package:habitly/features/gamification/domain/entities/user_stats.dart'
    as _i7;
import 'package:habitly/features/gamification/domain/repositories/gamification_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GamificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGamificationRepository extends _i1.Mock
    implements _i3.GamificationRepository {
  MockGamificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.UserLevel>> getUserLevel(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserLevel,
          [userId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.UserLevel>>.value(
            _FakeEither_0<_i5.Failure, _i6.UserLevel>(
          this,
          Invocation.method(
            #getUserLevel,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.UserLevel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.UserStats>> getUserStats(
    String? userId,
    _i7.StatsPeriod? period,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserStats,
          [
            userId,
            period,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i7.UserStats>>.value(
            _FakeEither_0<_i5.Failure, _i7.UserStats>(
          this,
          Invocation.method(
            #getUserStats,
            [
              userId,
              period,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.UserStats>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.HabitStats>>> getUserHabitsStats(
    String? userId,
    _i7.StatsPeriod? period,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserHabitsStats,
          [
            userId,
            period,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i8.HabitStats>>>.value(
                _FakeEither_0<_i5.Failure, List<_i8.HabitStats>>(
          this,
          Invocation.method(
            #getUserHabitsStats,
            [
              userId,
              period,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.HabitStats>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.Achievement>>> getAchievements(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAchievements,
          [userId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i9.Achievement>>>.value(
                _FakeEither_0<_i5.Failure, List<_i9.Achievement>>(
          this,
          Invocation.method(
            #getAchievements,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i9.Achievement>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i9.NewAchievementInfo>>> completeHabit(
    String? habitId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeHabit,
          [
            habitId,
            userId,
          ],
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.Failure, List<_i9.NewAchievementInfo>>>.value(
            _FakeEither_0<_i5.Failure, List<_i9.NewAchievementInfo>>(
          this,
          Invocation.method(
            #completeHabit,
            [
              habitId,
              userId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i9.NewAchievementInfo>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i10.GroupAchievement>>>
      getGroupAchievements(String? groupId) => (super.noSuchMethod(
            Invocation.method(
              #getGroupAchievements,
              [groupId],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i10.GroupAchievement>>>.value(
                _FakeEither_0<_i5.Failure, List<_i10.GroupAchievement>>(
              this,
              Invocation.method(
                #getGroupAchievements,
                [groupId],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i10.GroupAchievement>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i11.GroupStats>> getGroupStats(
    String? groupId,
    _i7.StatsPeriod? period,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupStats,
          [
            groupId,
            period,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i11.GroupStats>>.value(
            _FakeEither_0<_i5.Failure, _i11.GroupStats>(
          this,
          Invocation.method(
            #getGroupStats,
            [
              groupId,
              period,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i11.GroupStats>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> refreshData(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshData,
          [userId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #refreshData,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
