// Mocks generated by Mockito 5.4.6 from annotations
// in habitly/test/features/notifications/domain/usecases/get_notification_history_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:habitly/features/notifications/domain/entities/notification_history_item.dart'
    as _i5;
import 'package:habitly/features/notifications/domain/entities/notification_settings_snapshot.dart'
    as _i2;
import 'package:habitly/features/notifications/domain/repositories/notifications_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNotificationSettingsSnapshot_0 extends _i1.SmartFake
    implements _i2.NotificationSettingsSnapshot {
  _FakeNotificationSettingsSnapshot_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NotificationsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationsRepository extends _i1.Mock
    implements _i3.NotificationsRepository {
  MockNotificationsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> bootstrapNotificationPipeline(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #bootstrapNotificationPipeline,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.NotificationHistoryItem>> getHistory(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHistory,
          [userId],
        ),
        returnValue: _i4.Future<List<_i5.NotificationHistoryItem>>.value(
            <_i5.NotificationHistoryItem>[]),
      ) as _i4.Future<List<_i5.NotificationHistoryItem>>);

  @override
  _i4.Future<void> markRead(String? notificationId) => (super.noSuchMethod(
        Invocation.method(
          #markRead,
          [notificationId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.NotificationSettingsSnapshot> getSettings(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSettings,
          [userId],
        ),
        returnValue: _i4.Future<_i2.NotificationSettingsSnapshot>.value(
            _FakeNotificationSettingsSnapshot_0(
          this,
          Invocation.method(
            #getSettings,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.NotificationSettingsSnapshot>);

  @override
  _i4.Future<void> saveSettings(
    String? userId,
    _i2.NotificationSettingsSnapshot? settings,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSettings,
          [
            userId,
            settings,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
